import { AvatarPlaceholder } from "avatar_placeholder.slint";

export struct HmdToastItem {
    actor: string,
    action: string,
    avatar: image,
    has-avatar: bool,
    show-avatar: bool,
    relation-color: color,
    severity-color: color,
}

export component HmdToastPanel inherits Window {
    width: 960px;
    height: 528px;
    background: transparent;

    in property <bool> dark-background: true;
    in property <[HmdToastItem]> toasts: [];

    property <color> card-color: root.dark-background ? #101010eb : #101010b9;
    property <color> text-color: #eeeeee;

    for toast[index] in root.toasts : Rectangle {
        x: (root.width - 860px) / 2;
        y: root.height - 28px - 144px - index * 162px;
        width: 860px;
        height: 144px;
        visible: self.y >= 0px;
        background: root.card-color;
        property <length> content-x: toast.show-avatar ? 142px : 24px;
        property <length> content-width: self.width - self.content-x - 24px;

        Rectangle {
            x: 0px;
            y: 0px;
            width: 8px;
            height: parent.height;
            background: toast.severity-color;
        }

        AvatarPlaceholder {
            x: 24px;
            y: 24px;
            diameter: 96px;
            visible: toast.show-avatar && !toast.has-avatar;
        }

        Image {
            x: 24px;
            y: 24px;
            width: 96px;
            height: 96px;
            source: toast.avatar;
            visible: toast.show-avatar && toast.has-avatar;
        }

        Text {
            x: parent.content-x;
            y: 32px;
            width: parent.content-width;
            height: 36px;
            text: toast.actor;
            font-size: 30px;
            color: toast.relation-color;
        }

        Text {
            x: parent.content-x;
            y: 76px;
            width: parent.content-width;
            height: 29px;
            text: toast.action;
            font-size: 23px;
            color: root.text-color;
        }
    }
}
